<map version="freeplane 1.12.1">
<!--To view this file, download free mind mapping software Freeplane from https://www.freeplane.org -->
<bookmarks>
    <bookmark nodeId="ID_1090958577" name="Root" opensAsRoot="true"/>
</bookmarks>
<node TEXT="Template Repository" FOLDED="false" ID="ID_1090958577" CREATED="1409300609620" MODIFIED="1764833400969">
<hook NAME="accessories/plugins/AutomaticLayout.properties" VALUE="ALL"/>
<richcontent TYPE="NOTE">
<html>
  <head>
    
  </head>
  <body>
    <p>
      This mindmap contains templates to prepare various kinds of nodes in a Freeplane based mindmap, so that they can be rendered appropriately in a document generated by <a href="https://github.com/kraghuprasad/fp-convert">fp-convert</a>&#xa0;program. Please refer the <a href="https://github.com/kraghuprasad/fp-convert/blob/main/README.md">documentation</a>&#xa0;&#xa0;of <a href="https://github.com/kraghuprasad/fp-convert">fp-convert</a>&#xa0;to know more details about it.
    </p>
    <p>
      To know details of dynamic type creator script which can use these templates, please refer following links:
    </p>
    <p>
      &#xa0;&#xa0;&#xa0;&#xa0;* https://github.com/freeplane/freeplane/discussions/2365
    </p>
    <p>
      &#xa0;&#xa0;&#xa0;&#xa0;* https://github.com/i-plasm/freeplane-types-creator
    </p>
    <p>
      You should download and install <a http-equiv="content-type" content="text/html; charset=utf-8" title="dynamicTypesCreator.groovy" aria-label="dynamicTypesCreator.groovy, (File)" class="Link--primary" href="https://github.com/i-plasm/freeplane-types-creator/blob/main/dynamicTypesCreator.groovy" data-discover="true">dynamicTypesCreator.groovy</a>&#xa0;script from the repository listed above. The installation should be done in your local instance of freeplane tool. Then define a hotkey like Alt+T to execute that script on required nodes. That would ease creation of fp-convert compliant mindmaps for you.
    </p>
  </body>
</html></richcontent>
<hook NAME="MapStyle" background="#f5f5dcff">
    <properties edgeColorConfiguration="#808080ff,#ff0000ff,#0000ffff,#00ff00ff,#ff00ffff,#00ffffff,#7c0000ff,#00007cff,#007c00ff,#7c007cff,#007c7cff,#7c7c00ff" associatedTemplateLocation="template:/light_sepia_template.mm" followedTemplateLocation="template:/light_sepia_template.mm" showTagCategories="false" show_icon_for_attributes="true" auto_compact_layout="true" show_notes_in_map="true" show_tags="UNDER_NODES" show_note_icons="true" followedMapLastTime="1758277284000" fit_to_viewport="false" show_icons="BESIDE_NODES"/>
    <tags category_separator="::"/>

<map_styles>
<stylenode LOCALIZED_TEXT="styles.root_node" STYLE="oval" UNIFORM_SHAPE="true" VGAP_QUANTITY="24 pt">
<font SIZE="24"/>
<stylenode LOCALIZED_TEXT="styles.predefined" POSITION="bottom_or_right" STYLE="bubble">
<stylenode LOCALIZED_TEXT="default" ID="ID_1558627382" ICON_SIZE="12 pt" FORMAT_AS_HYPERLINK="false" COLOR="#2c2b29" BACKGROUND_COLOR="#eedfcc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="8 pt" SHAPE_VERTICAL_MARGIN="5 pt" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" VGAP_QUANTITY="3 pt">
<arrowlink SHAPE="CUBIC_CURVE" COLOR="#000000" WIDTH="2" TRANSPARENCY="200" DASH="" FONT_SIZE="9" FONT_FAMILY="SansSerif" DESTINATION="ID_1558627382" STARTINCLINATION="81.75 pt;0 pt;" ENDINCLINATION="81.75 pt;19.5 pt;" STARTARROW="NONE" ENDARROW="DEFAULT"/>
<font NAME="SansSerif" SIZE="9" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#2e3440" WIDTH="3" DASH="SOLID"/>
<richcontent TYPE="DETAILS" CONTENT-TYPE="plain/auto"/>
<richcontent TYPE="NOTE" CONTENT-TYPE="plain/auto"/>
</stylenode>
<stylenode LOCALIZED_TEXT="defaultstyle.details" COLOR="#ffffff" BACKGROUND_COLOR="#2e3440">
<font SIZE="10"/>
</stylenode>
<stylenode LOCALIZED_TEXT="defaultstyle.tags">
<font SIZE="10"/>
</stylenode>
<stylenode LOCALIZED_TEXT="defaultstyle.attributes">
<font SIZE="10"/>
</stylenode>
<stylenode LOCALIZED_TEXT="defaultstyle.note" COLOR="#000000" BACKGROUND_COLOR="#f6f9a1" TEXT_ALIGN="LEFT">
<icon BUILTIN="clock2"/>
<font SIZE="10" ITALIC="true"/>
</stylenode>
<stylenode LOCALIZED_TEXT="defaultstyle.floating">
<edge STYLE="hide_edge"/>
<cloud COLOR="#f0f0f0" SHAPE="ROUND_RECT"/>
</stylenode>
<stylenode LOCALIZED_TEXT="defaultstyle.selection" COLOR="#2c2b29" BACKGROUND_COLOR="#ffffff" BORDER_COLOR_LIKE_EDGE="false" BORDER_COLOR="#bf616a"/>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.user-defined" POSITION="bottom_or_right" STYLE="bubble">
<stylenode LOCALIZED_TEXT="styles.important" ID="ID_411331447" COLOR="#ffffff" BACKGROUND_COLOR="#bf616a" BORDER_COLOR="#bf616a">
<icon BUILTIN="yes"/>
<arrowlink COLOR="#bf616a" TRANSPARENCY="255" DESTINATION="ID_411331447"/>
<font NAME="Ubuntu" SIZE="12" BOLD="true"/>
<edge COLOR="#bf616a"/>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.flower" COLOR="#ffffff" BACKGROUND_COLOR="#255aba" STYLE="oval" TEXT_ALIGN="CENTER" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="22 pt" BORDER_COLOR_LIKE_EDGE="false" BORDER_COLOR="#f9d71c" BORDER_DASH_LIKE_EDGE="false" BORDER_DASH="CLOSE_DOTS" MAX_WIDTH="6 cm" MIN_WIDTH="3 cm"/>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.AutomaticLayout" POSITION="bottom_or_right" STYLE="bubble">
<stylenode LOCALIZED_TEXT="AutomaticLayout.level.root" COLOR="#ffffff" BACKGROUND_COLOR="#2c2b29" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="10 pt" SHAPE_VERTICAL_MARGIN="10 pt" BORDER_COLOR_LIKE_EDGE="false" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true">
<font SIZE="18"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,1" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="8 pt" SHAPE_VERTICAL_MARGIN="5 pt" BORDER_COLOR="#2c2b29">
<font SIZE="16"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,2" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="8 pt" SHAPE_VERTICAL_MARGIN="5 pt" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0">
<font SIZE="14"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,3" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="8 pt" SHAPE_VERTICAL_MARGIN="5 pt" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0">
<font SIZE="12"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,4" BACKGROUND_COLOR="#eedfcc" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0">
<font SIZE="11"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,5" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0">
<font SIZE="11"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,6" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0">
<font SIZE="10"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,7" BORDER_COLOR="#f0f0f0">
<font SIZE="10"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,8" BORDER_COLOR="#f0f0f0">
<font SIZE="10"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,9" BORDER_COLOR="#f0f0f0">
<font SIZE="10"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,10" BORDER_COLOR="#f0f0f0"/>
</stylenode>
</stylenode>
</map_styles>
</hook>
<node TEXT="Common Templates" FOLDED="true" POSITION="bottom_or_right" ID="ID_1495832884" CREATED="1743571867496" MODIFIED="1766403694189"><richcontent TYPE="NOTE">
<html>
  <head>
    
  </head>
  <body>
    <p>
      Common templates usable in a general document.
    </p>
  </body>
</html></richcontent>
<attribute_layout NAME_WIDTH="87 pt" VALUE_WIDTH="56.25 pt"/>
<attribute NAME="fpcBlockType" VALUE="Ignore"/>
<node TEXT="Template: Image" ID="ID_950440277" CREATED="1752088800613" MODIFIED="1766403543014">
<attribute_layout NAME_WIDTH="111 pt" VALUE_WIDTH="55.5 pt"/>
<attribute NAME="*fpcBlockType" VALUE="Image"/>
<attribute NAME="*fpcNotesPosition" VALUE="south"/>
<attribute NAME="*fpcShowCaption" VALUE="yes"/>
</node>
<node TEXT="Template: Verbatim" ID="ID_683498539" CREATED="1753968412713" MODIFIED="1766403547486">
<attribute_layout NAME_WIDTH="111 pt" VALUE_WIDTH="69 pt"/>
<attribute NAME="*fpcBlockType" VALUE="Verbatim"/>
<attribute NAME="*fpcNotesPosition" VALUE="south"/>
</node>
<node TEXT="Template: Verbatim Notes" ID="ID_1333761476" CREATED="1752088681854" MODIFIED="1766403566947">
<attribute_layout NAME_WIDTH="89.25 pt" VALUE_WIDTH="95.25 pt"/>
<attribute NAME="*fpcBlockType" VALUE="VerbatimNotes"/>
</node>
<node TEXT="Template: Stop Frame" ID="ID_372009767" CREATED="1754488613867" MODIFIED="1766403574979">
<attribute_layout NAME_WIDTH="92.25 pt" VALUE_WIDTH="75.75 pt"/>
<attribute NAME="*fpcBlocktype" VALUE="StopFrame"/>
</node>
<node TEXT="Template: Track Changes" ID="ID_1384230311" CREATED="1766581252628" MODIFIED="1766581276036">
<attribute_layout NAME_WIDTH="92.25 pt" VALUE_WIDTH="91.5 pt"/>
<attribute NAME="*fpcBlocktype" VALUE="TrackChanges"/>
</node>
<node TEXT="Template: Ignored Node" ID="ID_373636099" CREATED="1767008569327" MODIFIED="1767008596736">
<attribute_layout NAME_WIDTH="93.75 pt" VALUE_WIDTH="59.25 pt"/>
<attribute NAME="*fpcBlockType" VALUE="Ignore"/>
</node>
<node TEXT="Template: Page Break" ID="ID_124301729" CREATED="1767008448746" MODIFIED="1767008474659">
<attribute_layout NAME_WIDTH="93.75 pt" VALUE_WIDTH="78 pt"/>
<attribute NAME="*fpcBlockType" VALUE="PageBreak"/>
</node>
</node>
<node TEXT="Table Templates" FOLDED="true" POSITION="bottom_or_right" ID="ID_384485441" CREATED="1764683268645" MODIFIED="1766403687666">
<attribute_layout NAME_WIDTH="88.5 pt" VALUE_WIDTH="57.75 pt"/>
<attribute NAME="fpcBlockType" VALUE="Ignore"/>
<node TEXT="Template: Table" POSITION="bottom_or_right" ID="ID_898266934" CREATED="1764683113831" MODIFIED="1766403582061">
<attribute_layout NAME_WIDTH="93.75 pt" VALUE_WIDTH="50.25 pt"/>
<attribute NAME="*fpcBlockType" VALUE="Table"/>
</node>
<node TEXT="Template: Number Table" POSITION="bottom_or_right" ID="ID_1577076637" CREATED="1764683171983" MODIFIED="1766403591434">
<attribute_layout NAME_WIDTH="93.75 pt" VALUE_WIDTH="87.75 pt"/>
<attribute NAME="*fpcBlockType" VALUE="NumberTable"/>
</node>
</node>
<node TEXT="List Templates" FOLDED="true" POSITION="bottom_or_right" ID="ID_1571657878" CREATED="1753974178630" MODIFIED="1766403681016">
<attribute_layout NAME_WIDTH="88.5 pt" VALUE_WIDTH="57.75 pt"/>
<attribute NAME="fpcBlockType" VALUE="Ignore"/>
<richcontent TYPE="NOTE">
<html>
  <head>
    
  </head>
  <body>
    <p>
      Templates to render lists.
    </p>
  </body>
</html></richcontent>
<node TEXT="Template: Ordered List" ID="ID_1846200894" CREATED="1752078851995" MODIFIED="1766403600393">
<attribute_layout NAME_WIDTH="111 pt" VALUE_WIDTH="78.75 pt"/>
<attribute NAME="*fpcBlockType" VALUE="OrderedList"/>
<attribute NAME="*fpcNotesPosition" VALUE="north"/>
</node>
<node TEXT="Template: Unordered List" ID="ID_1017065751" CREATED="1752078894829" MODIFIED="1766403613191">
<attribute_layout NAME_WIDTH="92.25 pt" VALUE_WIDTH="90.75 pt"/>
<attribute NAME="*fpcBlocktype" VALUE="UnorderedList"/>
<attribute NAME="*fpcNotesPosition" VALUE="south"/>
</node>
</node>
<node TEXT="Project Templates" FOLDED="true" POSITION="bottom_or_right" ID="ID_649403774" CREATED="1743571867496" MODIFIED="1767940502548"><richcontent TYPE="NOTE">
<html>
  <head>
    
  </head>
  <body>
    <p>
      Project specific templates containing nodes for project, deliverable, meeting, risk,dbschema, etc.
    </p>
  </body>
</html></richcontent>
<attribute_layout NAME_WIDTH="88.5 pt" VALUE_WIDTH="57.75 pt"/>
<attribute NAME="fpcBlockType" VALUE="Ignore"/>
<node TEXT="Template: Project" POSITION="top_or_left" ID="ID_588680388" CREATED="1755668071868" MODIFIED="1766403621139">
<attribute_layout NAME_WIDTH="93.75 pt"/>
<attribute NAME="*fpcBlockType" VALUE="Project"/>
<node TEXT="Template Settings" ID="ID_1866884154" CREATED="1755671119580" MODIFIED="1755929843553">
<node TEXT="Title" ID="ID_468008892" CREATED="1755927852901" MODIFIED="1755929843553">
<attribute_layout NAME_WIDTH="101.25 pt"/>
<attribute NAME="destinationType" VALUE="core"/>
<attribute NAME="defaultText" VALUE="Project"/>
</node>
<node TEXT="Requirements" ID="ID_195000766" CREATED="1755671420068" MODIFIED="1755929843553">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="123.75 pt"/>
<attribute NAME="destinationType" VALUE="child"/>
<attribute NAME="*fpcBlockType" VALUE="requirements"/>
<attribute NAME="defaultText" VALUE="Requirements"/>
</node>
<node TEXT="Modules" ID="ID_1803888048" CREATED="1755671207118" MODIFIED="1755929843554">
<attribute_layout NAME_WIDTH="93.75 pt" VALUE_WIDTH="123.75 pt"/>
<attribute NAME="*fpcBlockType" VALUE="modules"/>
<attribute NAME="defaultText" VALUE="Modules"/>
<attribute NAME="destinationType" VALUE="child"/>
</node>
<node TEXT="Deliverables" ID="ID_156775778" CREATED="1755928914617" MODIFIED="1755929843554">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="84.75 pt"/>
<attribute NAME="*fpcBlockType" VALUE="deliverables"/>
<attribute NAME="dfaultText" VALUE="Deliverables"/>
<attribute NAME="destinationType" VALUE="child"/>
</node>
<node TEXT="Risks" ID="ID_252951428" CREATED="1755671355869" MODIFIED="1755929843554">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="72 pt"/>
<attribute NAME="*fpcBlockType" VALUE="risks"/>
<attribute NAME="defaultText" VALUE="Risks"/>
<attribute NAME="destinationType" VALUE="child"/>
</node>
</node>
</node>
<node TEXT="Template: Meeting" FOLDED="true" POSITION="top_or_left" ID="ID_491603540" CREATED="1743604919960" MODIFIED="1766403630377">
<attribute_layout NAME_WIDTH="88.5 pt" VALUE_WIDTH="66 pt"/>
<attribute NAME="*fpcBlockType" VALUE="Meeting"/>
<node TEXT="Template Settings" FOLDED="true" ID="ID_1463015507" CREATED="1744615842545" MODIFIED="1753256467857">
<node TEXT="Title" POSITION="top_or_left" ID="ID_549995539" CREATED="1746016575609" MODIFIED="1753256467858">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="174.74999 pt"/>
<attribute NAME="destinationType" VALUE="core"/>
<attribute NAME="defaultText" VALUE="Meeting conducted on {{today}}"/>
</node>
<node TEXT="Header: Participants" POSITION="top_or_left" ID="ID_818782287" CREATED="1761834254191" MODIFIED="1761834278135">
<attribute_layout NAME_WIDTH="93.75 pt" VALUE_WIDTH="81 pt"/>
<attribute NAME="*fpcBlockType" VALUE="participants"/>
</node>
<node TEXT="Participants" FOLDED="true" POSITION="top_or_left" ID="ID_1771930149" CREATED="1744615750756" MODIFIED="1761827753950">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="72 pt"/>
<attribute NAME="destinationType" VALUE="child"/>
<attribute NAME="comboType" VALUE="closed"/>
<attribute NAME="multiple" VALUE="true"/>
<attribute NAME="header" VALUE="Participants"/>
<node TEXT="&amp;List: People" ID="ID_666376619" CREATED="1744037199622" MODIFIED="1753256467858"/>
</node>
<node TEXT="Header: Agenda" POSITION="top_or_left" ID="ID_1938438307" CREATED="1761849843312" MODIFIED="1761849872991">
<attribute_layout NAME_WIDTH="93.75 pt" VALUE_WIDTH="61.5 pt"/>
<attribute NAME="*fpcBlockType" VALUE="agenda"/>
</node>
<node TEXT="Agenda" POSITION="top_or_left" ID="ID_449429601" CREATED="1744820101980" MODIFIED="1755928711916">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="72 pt"/>
<attribute NAME="destinationType" VALUE="child"/>
<attribute NAME="header" VALUE="Agenda"/>
</node>
<node TEXT="Header: Action Items" ID="ID_1689990809" CREATED="1761850368813" MODIFIED="1761850391584">
<attribute_layout NAME_WIDTH="93.75 pt" VALUE_WIDTH="59.25 pt"/>
<attribute NAME="*fpcBlockType" VALUE="actions"/>
</node>
<node TEXT="Action Items" POSITION="top_or_left" ID="ID_1359916652" CREATED="1744820139232" MODIFIED="1755928716407">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="72 pt"/>
<attribute NAME="destinationType" VALUE="child"/>
<attribute NAME="header" VALUE="Action Items"/>
</node>
</node>
</node>
<node TEXT="Template: Deliverable" FOLDED="true" POSITION="top_or_left" ID="ID_766990367" CREATED="1747640958172" MODIFIED="1766403632777">
<attribute_layout NAME_WIDTH="93.75 pt" VALUE_WIDTH="78.75 pt"/>
<attribute NAME="*fpcBlockType" VALUE="Deliverable"/>
<node TEXT="Template Settings" POSITION="top_or_left" ID="ID_1475510114" CREATED="1744816573826" MODIFIED="1755929843551">
<node TEXT="Title" ID="ID_327491287" CREATED="1747641925179" MODIFIED="1755929843551">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="80.25 pt"/>
<attribute NAME="destinationType" VALUE="core"/>
<attribute NAME="defaultText" VALUE="Deliverable"/>
</node>
<node TEXT="fpcId" ID="ID_1078850661" CREATED="1755362559501" MODIFIED="1755955302048">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="60.75 pt"/>
<attribute NAME="destinationType" VALUE="header"/>
</node>
<node TEXT="fpcAccountables" FOLDED="true" ID="ID_1219318258" CREATED="1744816596514" MODIFIED="1756022914031">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="72.75 pt"/>
<attribute NAME="comboType" VALUE="closed"/>
<attribute NAME="multiple" VALUE="true"/>
<attribute NAME="destinationType" VALUE="header"/>
<node TEXT="&amp;List: People" ID="ID_463633472" CREATED="1744037199622" MODIFIED="1755929843552"/>
</node>
<node TEXT="fpcDeliveryDate" ID="ID_685397685" CREATED="1747643518893" MODIFIED="1756015658892">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="72 pt"/>
<attribute NAME="destinationType" VALUE="header"/>
</node>
<node TEXT="fpcIsActive" ID="ID_1591309244" CREATED="1755363629419" MODIFIED="1756015729513">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="60.75 pt"/>
<attribute NAME="destinationType" VALUE="header"/>
<attribute NAME="defaultText" VALUE="yes"/>
</node>
<node TEXT="fpcDeliveredOn" ID="ID_54702842" CREATED="1767940596279" MODIFIED="1767940746202">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="92.25 pt"/>
<attribute NAME="destinationType" VALUE="header"/>
<attribute NAME="defaultText" VALUE="[Not Delivered]"/>
</node>
</node>
</node>
<node TEXT="Template: Risks" POSITION="top_or_left" ID="ID_1226545062" CREATED="1761828195187" MODIFIED="1766403640717">
<attribute_layout NAME_WIDTH="93.75 pt" VALUE_WIDTH="48 pt"/>
<attribute NAME="*fpcBlockType" VALUE="Risks"/>
</node>
<node TEXT="Template: Risk" FOLDED="true" POSITION="top_or_left" ID="ID_1307352825" CREATED="1747661840658" MODIFIED="1766403645350">
<attribute_layout NAME_WIDTH="93.75 pt" VALUE_WIDTH="43.5 pt"/>
<attribute NAME="*fpcBlockType" VALUE="Risk"/>
<node TEXT="Template Settings" ID="ID_818394880" CREATED="1747661850769" MODIFIED="1755929843555">
<node TEXT="Title" ID="ID_1188594991" CREATED="1747661860139" MODIFIED="1755929843555">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="48 pt"/>
<attribute NAME="destinationType" VALUE="core"/>
<attribute NAME="defaultText" VALUE="Risk"/>
</node>
<node TEXT="fpcId" ID="ID_426473536" CREATED="1755362559501" MODIFIED="1755955302048">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="60.75 pt"/>
<attribute NAME="destinationType" VALUE="header"/>
</node>
<node TEXT="fpcRiskTypes" ID="ID_933370685" CREATED="1747663122293" MODIFIED="1755955539495">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="60.75 pt"/>
<attribute NAME="comboType" VALUE="open"/>
<attribute NAME="multiple" VALUE="true"/>
<node TEXT="&amp;List: Risk Types" ID="ID_1423099488" CREATED="1747663126840" MODIFIED="1755929843555"/>
<node TEXT="Infrastructure" ID="ID_167801420" CREATED="1747663408812" MODIFIED="1755929843555"/>
</node>
<node TEXT="fpcIsActive" ID="ID_1775448192" CREATED="1755363629419" MODIFIED="1767940700685">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="60.75 pt"/>
<attribute NAME="destinationType" VALUE="header"/>
<attribute NAME="defaultText" VALUE="yes"/>
</node>
</node>
</node>
<node TEXT="Template: Database Schema" ID="ID_784160568" CREATED="1753291311352" MODIFIED="1766403655364">
<attribute_layout NAME_WIDTH="93.75 pt" VALUE_WIDTH="74.25 pt"/>
<attribute NAME="*fpcBlockType" VALUE="DBSchema"/>
</node>
</node>
<node TEXT="List: People" FOLDED="true" POSITION="top_or_left" ID="ID_1336652352" CREATED="1743603447217" MODIFIED="1767940531429">
<icon BUILTIN="broken-line"/>
<richcontent TYPE="NOTE">
<html>
  <head>
    
  </head>
  <body>
    <p>
      Following stakeholders are involved in various projects and tasks.
    </p>
  </body>
</html></richcontent>
<attribute_layout NAME_WIDTH="88.5 pt" VALUE_WIDTH="90.75 pt"/>
<attribute NAME="fpcBlockType" VALUE="Ignore"/>
<node TEXT="Ayesha Khanum" ID="ID_1095089636" CREATED="1751708806788" MODIFIED="1755929843558"><richcontent TYPE="NOTE">
<html>
  <head>
    
  </head>
  <body>
    <p>
      Primary role is that of Scrum Master. Facilitates smoot coordinations among all stakeholders, identifies road blocks and takes remedial actions. Brings up issues to the reporting authorities and other senior members of the team for timely resolutions.
    </p>
  </body>
</html></richcontent>
</node>
<node TEXT="Changu Bhai" ID="ID_536176217" CREATED="1743592869616" MODIFIED="1755929843558"><richcontent TYPE="NOTE">
<html>
  <head>
    
  </head>
  <body>
    <p>
      Primary role is that of System Designer.
    </p>
  </body>
</html></richcontent>
</node>
<node TEXT="Jayprakash Maurya" ID="ID_312761413" CREATED="1745221550520" MODIFIED="1755929843558"><richcontent TYPE="NOTE">
<html>
  <head>
    
  </head>
  <body>
    <p>
      Primary role is of Software Developer.
    </p>
  </body>
</html></richcontent>
</node>
<node TEXT="Jinesh Nair" ID="ID_1517013813" CREATED="1755370262221" MODIFIED="1755929843559"><richcontent TYPE="NOTE">
<html>
  <head>
    
  </head>
  <body>
    <p>
      Primary role is of Software Developer.
    </p>
  </body>
</html></richcontent>
</node>
<node TEXT="Mai In Jun" ID="ID_536367588" CREATED="1744012814616" MODIFIED="1755929843559"><richcontent TYPE="NOTE">
<html>
  <head>
    
  </head>
  <body>
    <p>
      Primary role is that of Language Translator. Proofreads technical documents and provides notes on quality of content.
    </p>
  </body>
</html></richcontent>
</node>
<node TEXT="Amanpreet Kaur" ID="ID_1387683968" CREATED="1755370467235" MODIFIED="1755929843559"><richcontent TYPE="NOTE">
<html>
  <head>
    
  </head>
  <body>
    <p>
      Primary role is Programme Manager.
    </p>
  </body>
</html></richcontent>
</node>
<node TEXT="Mallika Rajpurohit" ID="ID_800059622" CREATED="1743592885513" MODIFIED="1755929843559"><richcontent TYPE="NOTE">
<html>
  <head>
    
  </head>
  <body>
    <p>
      Primary role is that of Software Tester.
    </p>
  </body>
</html></richcontent>
</node>
<node TEXT="Viona D&apos;costa" ID="ID_1880736835" CREATED="1755370344925" MODIFIED="1755929843559"><richcontent TYPE="NOTE">
<html>
  <head>
    
  </head>
  <body>
    <p>
      Primary role is Project Manager.
    </p>
  </body>
</html></richcontent>
</node>
<node TEXT="Whoopie Bard" ID="ID_1810302773" CREATED="1743592893707" MODIFIED="1755929843560"><richcontent TYPE="NOTE">
<html>
  <head>
    
  </head>
  <body>
    <p>
      Primary role is that of Technical Writer.
    </p>
  </body>
</html></richcontent>
</node>
</node>
<node TEXT="UML Templates" FOLDED="true" POSITION="bottom_or_right" ID="ID_171329611" CREATED="1753974321275" MODIFIED="1766403667818">
<attribute_layout NAME_WIDTH="88.5 pt" VALUE_WIDTH="57.75 pt"/>
<attribute NAME="fpcBlockType" VALUE="Ignore"/>
<richcontent TYPE="NOTE">
<html>
  <head>
    
  </head>
  <body>
    <p>
      UML diagram specific templates.
    </p>
  </body>
</html></richcontent>
<node TEXT="Usecase Templates" POSITION="bottom_or_right" ID="ID_1923525478" CREATED="1753974103110" MODIFIED="1755929843556">
<attribute_layout NAME_WIDTH="88.5 pt" VALUE_WIDTH="57.75 pt"/>
<attribute NAME="fpcBlockType" VALUE="ignore"/>
<richcontent TYPE="NOTE">
<html>
  <head>
    
  </head>
  <body>
    <p>
      UML usecase diagram specific templates.
    </p>
  </body>
</html></richcontent>
<node TEXT="Template: Usecase Package" ID="ID_1085154687" CREATED="1743571882420" MODIFIED="1755929843556">
<attribute_layout NAME_WIDTH="108 pt" VALUE_WIDTH="78.75 pt"/>
<attribute NAME="*fpcBlockType" VALUE="UCPackage"/>
<attribute NAME="*fpcUCPDirection" VALUE="LR"/>
<node TEXT="Template Settings" ID="ID_1040078365" CREATED="1747322882227" MODIFIED="1755929843557">
<node TEXT="Title" ID="ID_1023370736" CREATED="1747322891290" MODIFIED="1755929897542">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="65.25 pt"/>
<attribute NAME="destinationType" VALUE="core"/>
<attribute NAME="defaultText" VALUE="Package"/>
</node>
</node>
</node>
<node TEXT="Template: Usecase Actors" ID="ID_1047187673" CREATED="1743571882420" MODIFIED="1755929843557">
<attribute_layout NAME_WIDTH="93.75 pt" VALUE_WIDTH="70.5 pt"/>
<attribute NAME="*fpcBlockType" VALUE="UCActors"/>
<node TEXT="Template Settings" LOCALIZED_STYLE_REF="default" ID="ID_1138168874" CREATED="1744820597303" MODIFIED="1744820601925">
<node TEXT="Title" ID="ID_1088123610" CREATED="1746268895132" MODIFIED="1755929905748">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="70.5 pt"/>
<attribute NAME="destinationType" VALUE="core"/>
<attribute NAME="defaultText" VALUE="Actors"/>
</node>
</node>
</node>
<node TEXT="Template: Usecase Actor" ID="ID_1532538472" CREATED="1748859003670" MODIFIED="1755929843557">
<attribute_layout NAME_WIDTH="100.5 pt" VALUE_WIDTH="83.25 pt"/>
<attribute NAME="*fpcStereoType" VALUE="&lt;&lt;human&gt;&gt;"/>
<attribute NAME="*fpcNotesDirection" VALUE="LO"/>
<node TEXT="Template Settings" LOCALIZED_STYLE_REF="default" ID="ID_299795622" CREATED="1748859373299" MODIFIED="1748860470368">
<node TEXT="Title" POSITION="bottom_or_right" ID="ID_1473208057" CREATED="1748859046737" MODIFIED="1755929912725">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="52.5 pt"/>
<attribute NAME="destinationType" VALUE="core"/>
<attribute NAME="defaultText" VALUE="Actor"/>
</node>
</node>
</node>
<node TEXT="Template: Usecase Action" ID="ID_1829100840" CREATED="1743590460019" MODIFIED="1755929843558">
<attribute_layout NAME_WIDTH="112.5 pt" VALUE_WIDTH="69.75 pt"/>
<attribute NAME="*fpcBlockType" VALUE="UCAction"/>
<attribute NAME="*fpcNotesDirection" VALUE="RO"/>
<node TEXT="Template Settings" LOCALIZED_STYLE_REF="default" ID="ID_125603629" CREATED="1744816573826" MODIFIED="1744816578478">
<node TEXT="Title" ID="ID_1571757322" CREATED="1756285617425" MODIFIED="1756285661646">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="56.25 pt"/>
<attribute NAME="destinationType" VALUE="core"/>
<attribute NAME="defaultText" VALUE="Action"/>
</node>
<node TEXT="Header: Preconditions" ID="ID_414557739" CREATED="1746113442916" MODIFIED="1747323944789">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="90.75 pt"/>
<attribute NAME="*fpcBlockType" VALUE="UCPre"/>
</node>
<node TEXT="Header: Normal Flow" ID="ID_1199013256" CREATED="1746114113897" MODIFIED="1747323949207">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="84.75 pt"/>
<attribute NAME="*fpcBlockType" VALUE="UCNF"/>
</node>
<node TEXT="Header: Alternate Flow" ID="ID_688039279" CREATED="1746114121390" MODIFIED="1747324035784">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="94.5 pt"/>
<attribute NAME="*fpcBlockType" VALUE="UCAF"/>
</node>
<node TEXT="Header: Exception Flow" ID="ID_361544298" CREATED="1746114127495" MODIFIED="1747312075417">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="95.25 pt"/>
<attribute NAME="*fpcBlocktype" VALUE="UCEF"/>
<attribute NAME="header" VALUE="Exception Flow"/>
</node>
<node TEXT="Header: Postconditions" ID="ID_133656076" CREATED="1746113474769" MODIFIED="1747324285553">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="94.5 pt"/>
<attribute NAME="*fpcBlockType" VALUE="UCPost"/>
</node>
<node TEXT="Preconditions" POSITION="bottom_or_right" ID="ID_1901452770" CREATED="1747312539017" MODIFIED="1747323728899">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="90.75 pt"/>
<attribute NAME="destinationType" VALUE="child"/>
<attribute NAME="header" VALUE="Preconditions"/>
</node>
<node TEXT="Normal Flow" POSITION="bottom_or_right" ID="ID_1656611198" CREATED="1747312561414" MODIFIED="1747323719456">
<attribute_layout NAME_WIDTH="103.5 pt" VALUE_WIDTH="84.75 pt"/>
<attribute NAME="destinationType" VALUE="child"/>
<attribute NAME="header" VALUE="Normal Flow"/>
</node>
<node TEXT="Alternate Flow" POSITION="bottom_or_right" ID="ID_649124562" CREATED="1747313004183" MODIFIED="1747323934759">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="94.5 pt"/>
<attribute NAME="destinationType" VALUE="child"/>
<attribute NAME="header" VALUE="Alternate Flow"/>
</node>
<node TEXT="Exception Flow" POSITION="bottom_or_right" ID="ID_755112325" CREATED="1747313123823" MODIFIED="1747323926094">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="95.25 pt"/>
<attribute NAME="destinationType" VALUE="child"/>
<attribute NAME="header" VALUE="Exception Flow"/>
</node>
<node TEXT="Postconditions" POSITION="bottom_or_right" ID="ID_1782322307" CREATED="1747313164703" MODIFIED="1747324272934">
<attribute_layout NAME_WIDTH="101.25 pt" VALUE_WIDTH="98.25 pt"/>
<attribute NAME="destinationType" VALUE="child"/>
<attribute NAME="header" VALUE="Postconditions"/>
</node>
</node>
</node>
</node>
</node>
<node TEXT="List: Risk Types" POSITION="top_or_left" ID="ID_1862848855" CREATED="1747662701353" MODIFIED="1767940526752">
<icon BUILTIN="broken-line"/>
<richcontent TYPE="NOTE">
<html>
  <head>
    
  </head>
  <body>
    <p>
      These are various known types of risks.
    </p>
  </body>
</html></richcontent>
<attribute_layout NAME_WIDTH="88.5 pt" VALUE_WIDTH="90.75 pt"/>
<attribute NAME="fpcBlockType" VALUE="Ignore"/>
<node TEXT="Compliance" ID="ID_950899374" CREATED="1747663080364" MODIFIED="1755929843560"><richcontent TYPE="NOTE">
<html>
  <head>
    
  </head>
  <body>
    <p>
      Compliance and legal risks.
    </p>
  </body>
</html></richcontent>
</node>
<node TEXT="Financial" ID="ID_1567580480" CREATED="1747662857393" MODIFIED="1755929843560"><richcontent TYPE="NOTE">
<html>
  <head>
    
  </head>
  <body>
    <p>
      Loss of capital or finances related risks.
    </p>
  </body>
</html></richcontent>
</node>
<node TEXT="Time" ID="ID_485787611" CREATED="1747662944717" MODIFIED="1755929843561"><richcontent TYPE="NOTE">
<html>
  <head>
    
  </head>
  <body>
    <p>
      Delay in execution or delivery related risks.
    </p>
  </body>
</html></richcontent>
</node>
</node>
<node TEXT="MacroGroup: Custom Macros" POSITION="top_or_left" ID="ID_1461784750" CREATED="1746016823611" MODIFIED="1766403735583" VSHIFT_QUANTITY="3.75 pt">
<attribute_layout NAME_WIDTH="88.5 pt" VALUE_WIDTH="57.75 pt"/>
<attribute NAME="fpcBlockType" VALUE="Ignore"/>
<node TEXT="{{today}}" ID="ID_1199160513" CREATED="1746016958356" MODIFIED="1755929843561"><richcontent TYPE="NOTE">
<html>
  <head>
    
  </head>
  <body>
    <p>
      <span style="font-size: 10pt;">new Date().format('dd-MM-yyyy') </span>
    </p>
  </body>
</html></richcontent>
</node>
</node>
<node TEXT="Testbed" POSITION="top_or_left" ID="ID_357897451" CREATED="1753972507834" MODIFIED="1767940538108">
<icon BUILTIN="broken-line"/>
<richcontent TYPE="NOTE">
<html>
  <head>
    
  </head>
  <body>
    <p>
      You may test creating nodes using supplied templates under this node.
    </p>
  </body>
</html></richcontent>
</node>
</node>
</map>
