#!/usr/bin/env python3
"""
A program to invoke Freeplane mindmap to PDF conversion utility. If the
mindmap is constructed, following certain conventions, one can produce
print-quality PDF documents using this program. It uses freeplane-io and
pylatex packages for the heavy-lifting.

Author: K Raghu Prasad <raghuprasad AT duck.com>
Copyright: ©2024-25 K. Raghu Prasad <raghuprasad AT duck.com>
ALL RIGHTS RESERVED.
"""
import logging
import string
import argparse
import os
import shutil
import sys
import tempfile
from pathlib import Path
from datetime import date

from fp_convert import __version__
from fp_convert.config import Config, create_config_from_file
from fp_convert.docs import GeneralDoc
from fp_convert.errors import FPConvertException
from fp_convert.utils.helpers import fetch_builders
from fp_convert.utils.fileproc import create_file_with_replaced_texts
from fp_convert.utils import builders
from fp_convert.utils.dbs import KNOWN_TYPES



def main():
    # Set up logging
    logger = logging.getLogger(__name__)
    formatter = logging.Formatter(
        "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    )
    stream_handler = logging.StreamHandler(stream=sys.stderr)
    stream_handler.setFormatter(formatter)
    if not logger.handlers:
        logger.addHandler(stream_handler)
    logger.setLevel(logging.INFO)
    logger.propagate = True

    parser = argparse.ArgumentParser(
        description="""
Program to convert a Freeplane mindmap's content into a print-quality PDF
document. If only relative file-paths are used in the mindmap to define
required resources like images, then run this program from within the directory
in which the mindmap file is situated. Otherwise, if absolute paths are used in
the resource-paths within the mindmap, then this program can be executed from
anywhere, as long as full paths of input and output files are provided to it.

By supplying option -i, a sample mindmap can be generated which can be opened
and modified in Freeplane mindmapping tool. This file contains samples of
all node-templates supported by fp-convert. Use Freeplane's dynamic type
creator plugin to use these templates while preparing the content in the
mindmap.

By supplying option -k, the TeX file generated by this program can be preserved
for inspection and further customization of the document. The generated TeX
file can be recompiled using the program pdflatex in any folder on the same
machine on which fp-convert was executed to generate it, except that it won't
contain the images created dynamically by fp-convert (like UML usecase
diagrams). This drawback would be taken care of in future releases.

By supplying option -g, a sample configuration file can be created. It can be
used to customize the styles and other parameters of the document generated by
this program.
    """
    )
    parser.add_argument(
        "mindmap_file", nargs="?", help="input freeplane mindmap file-path"
    )
    parser.add_argument("output_file", nargs="?", help="output PDF file-path")
    parser.add_argument(
        "-k",
        "--keep-tex",
        help="keep intermediate TeX/LaTeX file",
        action="store_true",
    )
    parser.add_argument(
        "-f",
        "--font-family",
        metavar="<font-family-name:font-family-options>",
        help=(
            """font-family to be used while building the PDF file
        Correct LaTeX options are required to be passed-on while supplying this
        parameter. Incorrect options, if supplied, would result in
        TeX-compilation failures. The option -k can be used to debug such
        issues by preserving the resultant TeX file for further inspection.
        Examples: roboto (The Roboto family of fonts to be used),
        roboto:sfdefault (The Roboto family along with LaTeX option sfdefault),
        roboto:sfdefault:scaled=1.1 (The Roboto family along with LaTeX options
        sfdefault and scaled=1.1 which are applicable on this font family),
        roboto:scaled=1.1 (The Roboto family of fonts scaled to 1.1), etc.
        Please ensure that invalid options for any font-family do not get
        supplied here.
        """
        ),
        default=None,
    )
    parser.add_argument(
        "-c",
        "--config",
        metavar="<config-file-to-be-used>",
        help=(
            "path to the YAML file with pertinent configuration "
            "parameters along with their default values which are "
            "required for converting a mindmap to PDF document"
        ),
    )
    parser.add_argument(
        "-d",
        "--debug",
        help="preserve all intermediate files for debugging purpose",
        action="store_true",
    )
    parser.add_argument(
        "-g",
        "--generate-config",
        metavar="<sample-config-file-to-be-created>",
        help=(
            "generates a sample configuration file of YAML type which "
            "contains all pertinent configuration parameters with their "
            "default values"
        ),
    )
    parser.add_argument(
        "-i",
        "--init-mindmap",
        metavar="<sample-mindmap-to-be-created>",
        help=(
            "generates a sample Freeplane mindmap file with applicable placeholder-"
            "texts which can be used as base to start an fp-convert compatible "
            "documentation project. It contains template-nodes required to "
            "generate various content-blocks of the docuement using Freeplane's "
            "dynamic type creator plugin."
        ),
    )
    parser.add_argument(
        "-v",
        "--version",
        help="print the version-number of fp-convert and exit",
        action="store_true",
    )

    args = parser.parse_args()

    if args.version:
        print(__version__)
        sys.exit(0)

    # Validate argument-setup
    if args.generate_config and (
        args.mindmap_file
        or args.output_file
        or args.config
        or args.debug
        or args.keep_tex
    ):
        print(
            "Either generate a configuration file (using -g or "
            "--generate-config) or use other allowed arguments to "
            "generate a PDF document. Cannot use both at the same time."
        )
        sys.exit(1)

    if args.generate_config:
        if os.path.exists(args.generate_config):
            print("The file {} already exists".format(args.generate_config))
            sys.exit(1)

        cnf = Config()

        # Ensure that the parent directory exists
        Path(args.generate_config).parent.mkdir(parents=True, exist_ok=True)

        # Write file-content with UTF-8 encoding
        with open(args.generate_config, "w", encoding="utf-8") as f:
            f.write(cnf.dump_yml())
        print(
            "Generated a sample configuration file {}".format(args.generate_config)
        )
        sys.exit(0)

    elif args.init_mindmap:
        if os.path.exists(args.init_mindmap):
            print("The file {} already exists".format(args.init_mindmap))
            sys.exit(1)

        # Ensure that the parent directory exists
        Path(args.init_mindmap).parent.mkdir(parents=True, exist_ok=True)


        # Create a new mindmap from the existing one embedded in the fp-convert distribution
        in_file = Path(os.path.join(
                os.path.dirname(__file__),
                "resources",
                "Template_Repository.mm")
        )
        out_file = Path(args.init_mindmap)

        # Create replacement-texts for the placeholder-texts
        replacements = {
            r"&lt;--Template Repository--&gt;": string.capwords(str.replace(out_file.stem, "_", " ")),
            r"&lt;--Today--&gt;": date.today().strftime("%d %B %Y"),
        }
        create_file_with_replaced_texts(in_file, out_file, replacements)
        print(
            "Generated mindmap file {}".format(args.init_mindmap)
        )
        sys.exit(0)

    elif args.mindmap_file is None or args.output_file is None:
        parser.print_help()
        sys.exit(1)

    # Get the input and output file-paths
    #
    mindmap_file_path = args.mindmap_file
    mm_filepath = Path(mindmap_file_path)
    output_pdf_path = args.output_file
    pdf_filepath = Path(output_pdf_path)

    temp_dir = tempfile.TemporaryDirectory(prefix="fp-convert-", delete=False)
    try:
        doc_kwargs: dict = {
            "working_dir": temp_dir.name,
        }
        if args.font_family:
            details = args.font_family.split(":")
            ff = list()
            ff_opts = list()
            ff.append(str.strip(details[0]))
            if len(details) > 1:
                for item in details[1:]:
                    ff_opts.append(str.strip(item))
            ff.append(ff_opts)
            doc_kwargs["font_family"] = ff
        else:
            doc_kwargs["font_family"] = ["lmodern", []]

        if args.config:
            cnf = create_config_from_file(args.config)
            doc_kwargs["config"] = cnf

            # If additional DB schema field-types are provided in the config file, add them
            # to the list of supported field-types
            for field_type in cnf.dbschema.additional_field_types:
                KNOWN_TYPES.add(field_type)

        if args.debug:
            logger.setLevel(logging.DEBUG)

        doc = GeneralDoc(
            mm_filepath,
            fetch_builders(builders),
            logger=logger,
            **doc_kwargs)

        temp_output = Path(temp_dir.name, f"{pdf_filepath.name}")

        try:  # Try building the PDF
            doc.generate_pdf(temp_output, clean=(not args.debug), clean_tex=(not args.keep_tex))
        except FPConvertException as e:
            print(e)
            sys.exit(1)

        shutil.copy2(str(temp_output), str(pdf_filepath))
        if args.keep_tex:
            shutil.copy2(
                Path(temp_dir.name, (pdf_filepath.stem + ".tex")),
                Path(pdf_filepath.parent, (pdf_filepath.stem + ".tex")),
            )
    except FPConvertException as e:
        print(e)
        sys.exit(1)
    finally:
        if not args.debug:
            temp_dir.cleanup()
        else:
            print(
                "Intermediate files have been preserved in directory: "
                f"{temp_dir.name}"
            )


if __name__ == "__main__":
    main()
